const breedDescriptions = {
    "Abyssinian": "Abyssinians are sleek, athletic, and one of the oldest known breeds. They're curious and love to climb.",
    "American Bobtail": "These cats have a natural bobbed tail, dog-like loyalty, and love interactive play.",
    "American Curl": "Known for their uniquely curled-back ears, they're friendly, affectionate, and love being around people.",
    "American Shorthair": "Adaptable and easygoing, these muscular cats are known for their hunting skills and sweet nature.",
    "American Wirehair": "Known for its unique crimped fur, this breed is playful, adaptable, and loves lounging just as much as playing.",
    "Australian Mist": "Friendly and tolerant, these spotted cats are great with kids and thrive in indoor environments.",
    "Balinese": "Elegant and vocal, the Balinese is basically a long-haired Siamese with the same intelligence and affection.",
    "Bengal": "With wild, leopard-like spots and high energy, Bengals are smart, active, and always ready to play.",
    "Birman": "Birmans are gentle, affectionate, and striking with their blue eyes and white-gloved paws.",
    "Bombay": "These sleek black cats are often called 'mini-panthers' and love human attention and lap time.",
    "British Longhair": "Fluffy and calm, this breed is affectionate but independent, with a plush teddy-bear look.",
    "British Shorthair": "Laid-back and dignified, these round-faced cuties are quiet, loyal, and easy to live with.",
    "Burmilla": "Charming and mischievous, Burmillas mix Burmese boldness with Chinchilla calm.",
    "California Spangled": "Designed to resemble wild cats, they're athletic, rare, and surprisingly people-oriented.",
    "Chartreux": "Quiet, loyal, and muscular, Chartreux cats are known for their thick blue-gray fur and smiley faces.",
    "Chausie": "A hybrid between domestic cats and jungle cats, Chausies are athletic, adventurous, and extremely active.",
    "Colorprint Shorthair": "Similar to the Siamese, they have striking color-point markings and are known for being vocal and affectionate.",
    "Cornish Rex": "With soft, curly fur and a mischievous spirit, Cornish Rex cats are playful, energetic, and full of personality.",
    "Cymric": "Basically a long-haired Manx, Cymrics are tailless fluffballs with loyal, gentle temperaments.",
    "Devon Rex": "Elfish looks and a clownish heart — they're intelligent, affectionate, and love attention.",
    "Donskoy": "Hairless and wrinkly, Donskoys are curious, social, and crave warmth and cuddles.",
    "Egyptian Mau": "One of the few naturally spotted breeds, they're fast, elegant, and often deeply bonded to their humans.",
    "European Burmese": "Softer in appearance than the American variety, they're sweet, social, and thrive on companionship.",
    "Exotic Longhair": "A Persian with longer legs and less drama — they're calm, affectionate, and love lounging around.",
    "Exotic Shorthair": "Like a plush teddy bear, they're laid-back, gentle, and ideal for people who want a Persian minus the grooming.",
    "Foldex": "A mix of Scottish Fold and Exotic Shorthair, Foldex cats are cuddly, calm, and wide-eyed charmers.",
    "Havana Brown": "With rich brown fur and green eyes, these cats are curious, intelligent, and love being part of the action.",
    "Himalayan": "A Persian-Siamese hybrid, they're quiet, gentle, and adore a peaceful, predictable home.",
    "Japanese Bobtail": "Playful and intelligent, they bring good luck in Japan and love to engage with their humans.",
    "Khao Manee": "Called the 'White Gem' of Thailand, these all-white cats with odd-colored eyes are rare, curious, and vocal.",
    "Kitler": "Loves to invade Poland. Will force France to surrender. Believes Jews are the worst.",
    "Korat": "Hailing from Thailand, Korats are silver-blue sweethearts known for being affectionate, observant, and loyal to one person.",
    "Kurillian Bobtail": "These muscular, short-tailed cats are playful, intelligent, and known for loving water and hunting.",
    "LaPerm": "Named for their curly coats, LaPerms are affectionate, quirky, and full of purring personality.",
    "Maine Coon": "The gentle giant of the cat world — friendly, fluffy, and great with families. Basically the golden retriever of cats.",
    "Manx": "Famous for having no tail, Manx cats are stout, agile, and loyal — often acting more like dogs than cats.",
    "Mekong Bobtail": "A Thai breed with a bobbed tail and Siamese-like coloring. Calm, clever, and full of charm.",
    "Minuet/Napoleon": "A cross between Persians and Munchkins, these cats are adorable, cuddly, and low-riders of the feline world.",
    "Monday Left Me Broken": ". Tuesday I was through with hopin' Wednesday my empty arms were open. Thursday waiting for love, waiting for love. ",
    "Munchkin": "Known for their short legs and big personalities, Munchkins are playful, curious, and totally unaware they're tiny.",
    "Nebelung": "Mysterious and elegant with long blue-gray fur, Nebelungs are shy at first but deeply affectionate once they trust you.",
    "Norwegian Forest": "Built like a Viking with fluff armor, these cats are independent, strong climbers, and surprisingly gentle giants.",
    "Ocicat": "Spotted like a wildcat but 100% domestic, Ocicats are social, active, and love attention from everyone — even strangers.",
    "Oriental Longhair": "Elegant and vocal with silky coats, they're affectionate, curious, and demand to be the center of attention.",
    "Oriental Shorthair": "With over 300 coat colors, this extroverted, chatty breed is the drama queen of the cat world — and they know it.",
    "Persians": "Low-energy, flat-faced royalty. They're quiet, affectionate, and spend most of their life serving looks while lounging.",
    "Peterbald": "A Russian sphynx-like breed, these curious, bald (or semi-bald) cats are friendly, elegant, and love physical contact.",
    "Pixiebob": "Looks like a mini wildcat but acts like a dog — Pixiebobs are loyal, chill, and great with kids and other pets.",
    "Ragamuffin": "Big, huggable, and sweet as hell — Ragamuffins melt in your arms and will follow you like a soft cloud on legs.",
    "Ragdoll": "Famously floppy when picked up, Ragdolls are gentle, affectionate, and love cuddling with their humans like living plushies.",
    "Russian Blue": "Shy at first but loyal for life, these plush, silver-coated introverts will quietly judge you from the shadows — lovingly.",
    "Savannah": "Part African serval, part domestic daredevil. Athletic, bold, and can jump onto your fridge like it's nothing.",
    "Scottish Fold": "Known for their folded ears and sweet round faces. Chill vibes only — unless you mess with dinner time.",
    "Selkirk Rex": "Like a curly teddy bear, this breed is affectionate, goofy, and always looks like they just rolled out of bed.",
    "Serengeti": "Spotted and sleek like a mini cheetah, Serengetis are vocal, high-energy, and born to zoom.",
    "Siamese": "Drama royalty. Hyper-social, loud, clingy, and smarter than your average human. They *will* own your soul.",
    "Siberian": "Built like a snow tank, Siberians are affectionate, bold, and surprisingly hypoallergenic for such a floof monster.",
    "Singapura": "Tiny but mighty. These pocket-sized extroverts are curious, playful, and never shy about being the center of attention.",
    "Snowshoe": "White-pawed and blue-eyed, Snowshoes are sweet-natured charmers with a touch of Siamese sass and sensitivity.",
    "Sokoke": "One of the rarest domestic cats, Sokokes are lean, fast, and prefer social circles smaller than a coffee date group chat.",
    "Somali": "A long-haired cousin of the Abyssinian — graceful, intelligent, and always ready for a dramatic tail flip.",
    "Sphynx": "Naked, warm, and outrageously clingy. These bald beauties love cuddles, heat lamps, and your undivided attention.",
    "Suphalak": "A rare Thai breed with deep chocolate fur and golden eyes, known for being affectionate, intelligent, and historically royal.",
    "Thai Lilac": "Soft-coated sweethearts with loving eyes and a calm demeanor. Like a lavender-scented nap in feline form.",
    "Tonkinese": "A playful mix of Siamese and Burmese, Tonkinese cats are affectionate extroverts who will *not* let you ignore them.",
    "Toyger": "Designed to look like a mini tiger, Toygers are confident, affectionate, and way more into playtime than actual hunting.",
    "Turkish Angora": "Elegant AF. These silky white floofs are smart, sassy, and carry themselves like they own the palace — because they do.",
    "Turkish Van": "A rare swimmer in the cat world. Loves water, climbing, and sometimes chaos. Basically a wet tornado in cat form.",
    "Ukranian Levkoy": "Wrinkly and hairless with inward-folding ears, they’re weird, sweet, and look like they’ve seen some things… and have opinions about them."
};