// Object to store breed descriptions (Madumi/Messy)
const breedDescriptions = {
    "Abyssinian": "Abyssinian cats originated in Ethiopia, live around 9-15 years, and are highly active, intelligent, and curious—constantly climbing, exploring, and seeking interaction.",
    "American Bobtail": "American Bobtail cats hail from the United States, live 13-15 years, and are friendly, energetic, playful, and loyal—often bonding deeply with their families.",
    "American Curl": "American Curl cats started in California, US, live approximately 12-16 years, and are known for their curled-back ears, gentle and affectionate personalities, and social, playful nature.",
    "American Shorthair": "American Shorthair cats evolved from European working cats in the US, live 15-20 years, and are adaptable, gentle, affectionate, healthy hunters suited to family life.",
    "American Wirehair": "American Wirehair cats were bred in New York, live 14-18 years, and are calm, affectionate, playful, and able to balance quiet lounging with interactive fun.",
    "Australian Mist": "Australian Mist cats come from Australia, live 10-15 years, and are friendly, tolerant, great with kids, and do well in indoor, family environments.",
    "Balinese": "Balinese cats were developed in the US from Siamese lines, live 15-20 years, and are elegant, vocal, intelligent, affectionate, and love playful conversation.",
    "Bengal": "Bengal cats, bred in the US from Asian leopard cats, live 12-16 years and are wild-looking, energetic, smart, vocal, and require plenty of mental and physical play.",
    "Birman": "Birman cats come from Burma, live 12-16 years, and are gentle, affectionate, calm companions who love quiet cuddles and serene environments.",
    "Bombay": "Bombay cats, developed in the US to resemble mini-panthers, live 12-16 years and are sleek, confident, affectionate, outgoing, and attention-loving lap cats.",
    "British Longhair": "British Longhair cats originated in the UK, live 12-16 years, and are fluffy, calm, affectionate, yet independent, with a plush teddy-bear appearance.",
    "British Shorthair": "British Shorthair cats come from the UK, live 12-20 years, and are laid-back, dignified, quiet, loyal, and ideal for easygoing homes.",
    "Burmilla": "Burmilla cats originated in the UK, live 10-15 years, and are charming, mischievous, sociable, affectionate, blending Burmese boldness with Chinchilla calm.",
    "California Spangled": "California Spangled cats were developed in the US to mimic wild cats, live around 12-15 years, and are athletic, rare, intelligent, and surprisingly people-oriented.",
    "Chartreux": "Chartreux cats come from France, live 12-15 years, and are quiet, loyal, muscular, sweet-natured companions known for their thick blue-gray coats and gentle smiles.",
    "Chausie": "Chausie cats are hybrids of domestic and jungle cats (mainly from the US), live 12-16 years, and are athletic, adventurous, extremely active, and need ample space to roam.",
    "Colorpoint Shorthair": "Colorpoint Shorthair cats, developed in the US from Siamese lines, live 12-15 years and are affectionate, vocal, social, and enjoy close human companionship.",
    "Cornish Rex": "Cornish Rex cats originated in Cornwall, England, live 11-15 years, and are soft-coated, spirited, playful, energetic, sharp, and full of personality.",
    "Cymric": "Cymric cats, the long-haired Manx from the Isle of Man, live 8-14 years and are tailless, loyal, gentle, and affectionate with dog-like traits.",
    "Devon Rex": "Devon Rex cats from Devon, England, live 10-15 years, and are elfin-faced, mischievous, affectionate, intelligent, and crave playful attention.",
    "Donskoy": "Donskoy cats originated in Russia, live around 12-15 years, and are hairless, curious, social, and always seeking warmth and affection.",
    "Egyptian Mau": "Egyptian Mau cats hail from Egypt, live 12-15 years, and are sleek, naturally spotted, lightning-fast, and fiercely loyal to their humans.",
    "European Burmese": "European Burmese cats developed in the UK, live about 10-15 years, and are affectionate, social, playful, and thrive on constant companionship.",
    "Exotic Longhair": "Exotic Longhair cats come from crossbreeding Persians, live 12-16 years, and are sweet, laid-back, fluffy charmers who love to lounge peacefully.",
    "Exotic Shorthair": "Exotic Shorthair cats were bred in the US from Persians, live 12-15 years, and are calm, gentle, affectionate, and need less grooming than Persians.",
    "Foldex": "Foldex cats, a Canadian mix of Exotic Shorthair and Scottish Fold, live 12-15 years, and are adorable, calm, cuddly, and irresistibly wide-eyed.",
    "Havana Brown": "Havana Browns, bred in England, live 12-15 years, and are sleek, chocolate-colored charmers with bright green eyes, curiosity, and a need for involvement.",
    "Himalayan": "Himalayan cats, a US-bred Persian-Siamese mix, live 9-15 years, and are gentle, quiet, loving, and happiest in serene, stable homes.",
    "Japanese Bobtail": "Japanese Bobtails originate from Japan, live 12-16 years, and are energetic, intelligent, chatty, lucky symbols that thrive on human interaction.",
    "Khao Manee": "Khao Manee cats from Thailand live 10-12 years, are pure white, often odd-eyed, rare, vocal, and brimming with curiosity.",
    "Kitler": "Kitler was a domestic shorthair cat known for his distinct black mustache marking, which led to his controversial nickname. Born in Austria in the early 20th century, he was noted for his territorial behavior, often dominating food bowls and sleeping areas. Kitler preferred isolation from other animals, especially those not from his 'approve' inner circle. He was vocal, especially at night, often meowing loudly as if delivering speeches. His aggressive tendencies extended to attempts at controlling the entire house, including spaces designated for dogs. Eventually, his reign ended abruptly in 1945 when he disappeared without a trace.",
    "Korat": "Korats, the silver-blue charmers from Thailand, live 12-15 years, and are affectionate, intelligent, and deeply loyal to their chosen human.",
    "Kurilian Bobtail": "Kurilian Bobtails from Russia and Japan live 14-20 years, are strong, playful, love water, and are skilled hunters with short fluffy tails.",
    "LaPerm": "LaPerms, developed in the US, live 10-15 years, and are curly-coated, loving, quirky, and full of personality and gentle mischief.",
    "Maine Coon": "Maine Coons from the US live 12-15 years, are giant, friendly fluffballs who are sociable, dog-like, and perfect for families.",
    "Manx": "Manx cats from the Isle of Man live 12-16 years, are tailless, agile, loyal, and often behave more like dogs than felines.",
    "Mekong Bobtail": "Mekong Bobtails from Thailand and Russia live 12-15 years, are calm, intelligent, blue-eyed cuties with bobbed tails and Siamese-like vibes.",
    "Minuet/Napoleon": "Minuet cats, a Persian-Munchkin mix from the US, live 9-15 years, and are adorably short-legged, affectionate, and sweet-tempered companions.",
    "Monday Left Me Broken": "Monday left me broken. Tuesday I was through with hopin' Wednesday my empty arms were open. Thursday waiting for love, waiting for love.",
    "Munchkin": "Munchkins, first bred in the US, live 12-15 years, and are playful, fearless, short-legged bundles of joy that never notice their height.",
    "Nebelung": "Nebelungs from the US live 11-18 years, are long-haired, blue-gray, and affectionate once bonded, though shy with strangers.",
    "Norwegian Forest": "Norwegian Forest cats from Scandinavia live 14-16 years, are large, sturdy climbers with thick coats and gentle personalities.",
    "Ocicat": "Ocicats from the US live 12-15 years, look wild but are fully domestic — active, social, and friendly to strangers and families alike.",
    "Oriental Longhair": "Oriental Longhairs, related to Siamese, live 12-15 years, are silky-coated, talkative, curious, and attention-seeking beauties.",
    "Oriental Shorthair": "Oriental Shorthairs from the US live 12-15 years, are sleek, vocal, extroverted, and come in 300+ coat colors. Total drama queens.",
    "Persian": "Persians, ancient and regal, live 10-15 years, are quiet, affectionate, and known for their luxurious coats and flat faces.",
    "Peterbald": "Peterbalds from Russia live 12-15 years, are bald or velvety-skinned, affectionate, curious, and clingy in the best way.",
    "Pixiebob": "Pixiebobs from the US live 13-16 years, are bobtailed, wild-looking but dog-like in loyalty, and great with families and pets.",
    "Ragamuffin": "Ragamuffins from the US live 12-16 years, are large, cuddly, and ultra-sweet — they go limp when held and adore attention.",
    "Ragdoll": "Ragdolls from the US live 12-17 years, are big, floppy, affectionate lap cats that love people and thrive on companionship.",
    "Russian Blue": "Russian Blues from Russia live 15-20 years, are plush, silver-coated introverts who form deep, quiet bonds with their humans.",
    "Savannah": "Savannah cats, a mix of African serval and domestic breeds, live 12-20 years, are tall, wild-looking, bold, and high-energy.",
    "Scottish Fold": "Scottish Folds from Scotland live 11-14 years, are known for their folded ears, sweet expressions, and mellow, gentle vibes.",
    "Selkirk Rex": "Selkirk Rex cats from the US live 14-15 years, have plush, curly coats and easygoing, cuddly, slightly goofy personalities.",
    "Serengeti": "Serengetis from the US live 10-15 years, are spotted, athletic, talkative, and bred to look like wild cats without the wild behavior.",
    "Siamese": "Siamese cats from Thailand live 12-20 years, are loud, social, clingy, and highly intelligent — true drama royalty of the cat world.",
    "Siberian": "Siberians from Russia live 11-18 years, are large, bold, affectionate, and hypoallergenic despite their dense triple coat.",
    "Singapura": "Singapuras from Singapore live 11-15 years, are one of the smallest cat breeds — playful, extroverted, and full of confidence.",
    "Snowshoe": "Snowshoes from the US live 12-15 years, are medium-sized with white paws, blue eyes, and a gentle, affectionate temperament.",
    "Sokoke": "Sokokes from Kenya live 10-15 years, are rare, lean, fast, and prefer a quiet, close-knit social circle.",
    "Somali": "Somalis from the US live 12-16 years, are fox-like with long fur, curious minds, and graceful, athletic energy.",
    "Sphynx": "Sphynx cats from Canada live 9-15 years, are bald, warm, affectionate, and crave constant attention and cuddles.",
    "Suphalak": "Suphalaks from Thailand live 12-16 years, are rare, chocolate-colored, golden-eyed, and historically linked to Thai royalty.",
    "Thai Lilac": "Thai Lilacs from Thailand live 12-16 years, are soft-coated, calm, affectionate, and have a gentle, loving presence.",
    "Tonkinese": "Tonkinese cats from the US live 12-16 years, are playful, talkative, loving extroverts — a perfect Siamese-Burmese blend.",
    "Toyger": "Toygers from the US live 10-15 years, are bred to look like tiny tigers — confident, social, and energetic playmates.",
    "Turkish Angora": "Turkish Angoras from Turkey live 12-18 years, are elegant, intelligent, and carry themselves with sass and grace.",
    "Turkish Van": "Turkish Vans from Turkey live 12-17 years, are large, athletic, and famously fond of swimming and mischief.",
    "Ukrainian Levkoy": "Ukrainian Levkoys from Ukraine live 12-15 years, are hairless with folded ears — affectionate, odd-looking, and full of quirky charm."
};