const link = {
    "Abyssinian" : "https://en.wikipedia.org/wiki/Abyssinian_cat",
    "American Bobtail" : "https://en.wikipedia.org/wiki/American_Bobtail",
    "American Curl" : "https://en.wikipedia.org/wiki/American_Curl",
    "American Shorthair" : "https://en.wikipedia.org/wiki/American_Shorthair",
    "American Wirehair" : "https://en.wikipedia.org/wiki/American_Wirehair",
    "Australian Mist" : "https://en.wikipedia.org/wiki/Australian_Mist",
    "Bengal" : "https://en.wikipedia.org/wiki/Bengal_cat",
    "Birman" : "https://en.wikipedia.org/wiki/Birman",
    "Bombay" : "https://en.wikipedia.org/wiki/Bombay_cat",
    "British Longhair": "https://en.wikipedia.org/wiki/British_Longhair",
    "British Shorthair" : "https://en.wikipedia.org/wiki/British_Shorthair",
    "Burmilla" : "https://en.wikipedia.org/wiki/Burmilla",
    "Burmese" : "https://en.wikipedia.org/wiki/Burmese_cat",
    "California Spangled" : "https://en.wikipedia.org/wiki/California_Spangled",
    "Chartreux" : "https://en.wikipedia.org/wiki/Chartreux",
    "Chausie" : "https://en.wikipedia.org/wiki/Chausie",
    "Colorpoint Shorthair" : "https://en.wikipedia.org/wiki/Colorpoint_Shorthair",
    "Cornish Rex" : "https://en.wikipedia.org/wiki/Cornish_Rex",    
    "Cymric" : "https://en.wikipedia.org/wiki/Cymric",
    "Devon Rex" : "https://en.wikipedia.org/wiki/Devon_Rex",
    "Donskoy" : "https://en.wikipedia.org/wiki/Donskoy",
    "Egyptian Mau" : "https://en.wikipedia.org/wiki/Egyptian_Mau",
    "El Gato" : "https://meme-cats.fandom.com/wiki/El_Gato",
    "European Burmese" : "https://en.wikipedia.org/wiki/European_Burmese",
    "Exotic Longhair" : "https://en.wikipedia.org/wiki/Exotic_Longhair",
    "Exotic Shorthair" : "https://en.wikipedia.org/wiki/Exotic_Shorthair",
    "Foldex" : "https://en.wikipedia.org/wiki/Foldex",
    "Havana Brown" : "https://en.wikipedia.org/wiki/Havana_Brown",
    "Himalayan" : "https://en.wikipedia.org/wiki/Himalayan_cat",
    "Japanese Bobtail" : "https://en.wikipedia.org/wiki/Japanese_Bobtail",
    "Khao Manee" : "https://en.wikipedia.org/wiki/Khao_Manee",
    "Kitler" : "https://en.wikipedia.org/wiki/Kitler",
    "Korat" : "https://en.wikipedia.org/wiki/Korat",
    "Kurilian Bobtail" : "https://en.wikipedia.org/wiki/Kurilian_Bobtail",
    "LaPerm": "https://en.wikipedia.org/wiki/LaPerm",
    "Maine Coon" : "https://en.wikipedia.org/wiki/Maine_Coon",
    "Manx" : "https://en.wikipedia.org/wiki/Manx",
    "Mekong Bobtail" : "https://en.wikipedia.org/wiki/Mekong_Bobtail",
    "Minuet/Napoleon" : "https://en.wikipedia.org/wiki/Minuet_cat",
    "Monday Left Me Broken" : "https://meme.fandom.com/wiki/Monday_Left_Me_Broken_Cat",
    "Munchkin" : "https://en.wikipedia.org/wiki/Munchkin",
    "Nebelung" : "https://en.wikipedia.org/wiki/Nebelung",
    "Norwegian Forest" : "https://en.wikipedia.org/wiki/Norwegian_Forest",
    "Ocicat" : "https://en.wikipedia.org/wiki/Ocicat",
    "O I I A I" : "https://en.namu.wiki/w/Oiia%20Cat",
    "Oriental Longhair" : "https://en.wikipedia.org/wiki/Oriental_Longhair",
    "Oriental Shorthair" : "https://en.wikipedia.org/wiki/Oriental_Shorthair",
    "Persian" : "https://en.wikipedia.org/wiki/Persian_cat",
    "Peterbald" : "https://en.wikipedia.org/wiki/Peterbald",
    "Pixiebob" : "https://en.wikipedia.org/wiki/Pixiebob",
    "Polite Cat" : "https://meme.fandom.com/wiki/Polite_Cat",
    "Ragamuffin" : "https://en.wikipedia.org/wiki/Ragamuffin_cat",
    "Ragdoll" : "https://en.wikipedia.org/wiki/Ragdoll",
    "Russian Blue" : "https://en.wikipedia.org/wiki/Russian_Blue",
    "Savannah" : "https://en.wikipedia.org/wiki/Savannah_cat",
    "Scottish Fold" : "https://en.wikipedia.org/wiki/Scottish_Fold_cat",
    "Seilkirk Rex" : "https://en.wikipedia.org/wiki/Selkirk_Rex",
    "Serengeti" : "https://en.wikipedia.org/wiki/Serengeti_cat",
    "Siamese" : "https://en.wikipedia.org/wiki/Siamese_cat",
    "Siberian" : "https://en.wikipedia.org/wiki/Siberian_cat",
    "Singapura" : "https://en.wikipedia.org/wiki/Singapura",
    "Snowshoe" : "https://en.wikipedia.org/wiki/Snowshoe_cat",
    "Sokoke" : "https://en.wikipedia.org/wiki/Sokoke",
    "Somali" : "https://en.wikipedia.org/wiki/Somali_cat",
    "Sphynx" : "https://en.wikipedia.org/wiki/Sphynx",
    "Suphalak" : "https://en.wikipedia.org/wiki/Suphalak",
    "Thai Lilac" : "https://en.wikipedia.org/wiki/Thai_Lilac",
    "Tonkinese" : "https://en.wikipedia.org/wiki/Tonkinese_cat",
    "Toyger" : "https://en.wikipedia.org/wiki/Toyger",
    "Turkish Angora" : "https://en.wikipedia.org/wiki/Turkish_Angora",
    "Turkish Van" : "https://en.wikipedia.org/wiki/Turkish_Van",
    "Ukrainian Levkoy" : "https://en.wikipedia.org/wiki/Ukrainian_Levkoy",

}